//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebYemekSiparisi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanici()
        {
            this.satislar = new HashSet<satislar>();
        }
    
        public int id { get; set; }
        public string kullaniciad { get; set; }
        public string sifre { get; set; }
        public bool admin { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tcno { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string ilce { get; set; }
        public string il { get; set; }
        public bool silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satislar> satislar { get; set; }
    }
}
