//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebYemekSiparisi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public satislar()
        {
            this.satisdetaylari = new HashSet<satisdetaylari>();
        }
    
        public int satisno { get; set; }
        public System.DateTime tarih { get; set; }
        public int kullanicino { get; set; }
        public decimal tutar { get; set; }
        public int miktar { get; set; }
        public System.DateTime teslimtarihi { get; set; }
        public byte durumu { get; set; }
        public bool silindi { get; set; }
    
        public virtual kullanici kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satisdetaylari> satisdetaylari { get; set; }
    }
}
