//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebYemekSiparisi.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yemeksiparisiEntities1 : DbContext
    {
        public yemeksiparisiEntities1()
            : base("name=yemeksiparisiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<altmenu> altmenu { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<satisdetaylari> satisdetaylari { get; set; }
        public virtual DbSet<satislar> satislar { get; set; }
        public virtual DbSet<urun> urun { get; set; }
    }
}
